### ISSUE TITLE
Server "npm run coverage" fails on Windows

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/pcyl-web#54]
Mike gets the following error output when running "npm run coverage"

    C:\Users\Mike\git\pcyl-web>npm run coverage
    
    > pcyl-web-server@0.0.0 coverage C:\Users\Mike\git\pcyl-web
    > istanbul cover _mocha
    
    No coverage information was collected, exit without writing coverage information
    C:\Users\Mike\git\pcyl-web\node_modules\.bin\_mocha.CMD:1
    (function (exports, require, module, __filename, __dirname) { @IF EXIST "%~dp0\node.exe" (
                                                                 ^
    
    SyntaxError: Invalid or unexpected token
       at createScript (vm.js:56:10)
       at Object.runInThisContext (vm.js:97:10)
       at Module._compile (module.js:549:28)
       at Object.Module._extensions..js (module.js:586:10)
       at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\Mike\git\pcyl-web\node_modules\istanbul\lib\hook.js:109:37)
       at Module.load (module.js:494:32)
       at tryModuleLoad (module.js:453:12)
       at Function.Module._load (module.js:445:3)
       at Function.Module.runMain (module.js:611:10)
       at runFn (C:\Users\Mike\git\pcyl-web\node_modules\istanbul\lib\command\common\run-with-cover.js:122:16)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! pcyl-web-server@0.0.0 coverage: `istanbul cover _mocha`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the pcyl-web-server@0.0.0 coverage script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\Mike\AppData\Roaming\npm-cache\_logs\2018-07-29T02_29_17_702Z-debug.log

**Comment by 1fifoto** [comment]
Doing a Google search for "windows instanbul mocha fails" suggests changing "_mocha" to fully-qualified "node_modules/mocha/bin/_mocha"

**Comment by 1fifoto** [comment]
Merged into master, closing
